name: Manual trigger to build artifacts

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-tags: true
    - name: Install packages
      uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: msitools wixl
        version: 1.0
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
    - name: Install linter
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2

    - name: Build Msi
      run: |
        echo "version=$(cat VERSION)" >> $GITHUB_ENV
        make msi
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: agent-autoupdate-${{ env.version }}.msi
        path: ./packaging/agent-autoupdate-*.msi
