name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # env:
    #   GL_DEBUG: "loader"
    runs-on: windows-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-tags: true
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        args: --timeout=5m -v
        version: v1.64
    - name: Build
      run: make build
    - name: Authenticate GitHub CLI
      run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
    - name: Create GitHub Release and Upload .exe
      run: |
        gh release delete latest --yes || true
        gh release create latest ./packaging/agent-autoupdate.exe \
          --title "Latest Release" \
          --notes "Automated release" \
          --target ${{ github.sha }}
